-- Remove SeatMap-related tables and columns
-- This migration removes the SeatMap feature which was never used in production

-- Drop SeatReservation table first (has FK to EventDate)
DROP TABLE IF EXISTS "SeatReservation";

-- Drop foreign key constraints before dropping columns
-- Note: These constraint names are generated by Prisma. If they differ in your environment,
-- adjust accordingly or use: ALTER TABLE ... DROP CONSTRAINT IF EXISTS ...
ALTER TABLE "Event" DROP CONSTRAINT IF EXISTS "Event_seatMapId_fkey";
ALTER TABLE "Order" DROP CONSTRAINT IF EXISTS "Order_seatMapId_fkey";

-- Drop columns from Event
ALTER TABLE "Event" DROP COLUMN IF EXISTS "seatMapId";
ALTER TABLE "Event" DROP COLUMN IF EXISTS "seatType";

-- Drop column from Order
ALTER TABLE "Order" DROP COLUMN IF EXISTS "seatMapId";

-- Drop column from Ticket
ALTER TABLE "Ticket" DROP COLUMN IF EXISTS "seatId";

-- Drop SeatMap table
DROP TABLE IF EXISTS "SeatMap";
